[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["rm -rf node_modules", "npm cache clean --force", "npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"